modLoader="javafml"
loaderVersion="[4,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/quek04/astronomica/issues" #optional

[[mods]] #mandatory
modId="astronomica" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Astronomica" #mandatory
authors="quek" #optional
description='''Venture forth into Astronomica'''

[[dependencies.astronomica]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[21.1.0,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.astronomica]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"